### PR TITLE
Minor changes

### PR DESCRIPTION
**Pull request by bernfarr**
Fix some typos. Add links to the primary web site for various defined
terms. Re-order the terms list so the definition for React appears
before other React-related definitions
Updated ES7 definition as it's been finalized.

### CODE REVIEW

**Comment by codylindley** [comment]
Appreciate you making this better.

**Comment by bernfarr** [comment]
@codylindley I'm looking at the section on **Writing React With JSFiddle** (3.4.md). It has a pointer to the React Base Fiddle and the text mentions that this includes three JS files
1. react.js
1. react-dom.js, and
1. browser.js

However that JSFiddle only uses two different JS files, see below.
image

I can modify the text appropriately. But should I also change the text in this section that refers to the use of Babel 5.8.23 as these JSFiddle does the transformation without referring directly to Babel?

**Comment by codylindley** [comment]
It uses it too i.e. https://fiddle.jshell.net/js/babel/babel.js. Maybe I should just say, the jsfiddle already includes it.

**Comment by bernfarr** [comment]
Thanks for clarifying. I'll just correct the text for the React JS file names.

**Pull request merged**
